package com.itraing.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.itraing.greendao.DeviceBean;
import com.itraing.greendao.LostBean;
import com.itraing.greendao.LocationBean;

import com.itraing.greendao.DeviceBeanDao;
import com.itraing.greendao.LostBeanDao;
import com.itraing.greendao.LocationBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceBeanDaoConfig;
    private final DaoConfig lostBeanDaoConfig;
    private final DaoConfig locationBeanDaoConfig;

    private final DeviceBeanDao deviceBeanDao;
    private final LostBeanDao lostBeanDao;
    private final LocationBeanDao locationBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceBeanDaoConfig = daoConfigMap.get(DeviceBeanDao.class).clone();
        deviceBeanDaoConfig.initIdentityScope(type);

        lostBeanDaoConfig = daoConfigMap.get(LostBeanDao.class).clone();
        lostBeanDaoConfig.initIdentityScope(type);

        locationBeanDaoConfig = daoConfigMap.get(LocationBeanDao.class).clone();
        locationBeanDaoConfig.initIdentityScope(type);

        deviceBeanDao = new DeviceBeanDao(deviceBeanDaoConfig, this);
        lostBeanDao = new LostBeanDao(lostBeanDaoConfig, this);
        locationBeanDao = new LocationBeanDao(locationBeanDaoConfig, this);

        registerDao(DeviceBean.class, deviceBeanDao);
        registerDao(LostBean.class, lostBeanDao);
        registerDao(LocationBean.class, locationBeanDao);
    }
    
    public void clear() {
        deviceBeanDaoConfig.getIdentityScope().clear();
        lostBeanDaoConfig.getIdentityScope().clear();
        locationBeanDaoConfig.getIdentityScope().clear();
    }

    public DeviceBeanDao getDeviceBeanDao() {
        return deviceBeanDao;
    }

    public LostBeanDao getLostBeanDao() {
        return lostBeanDao;
    }

    public LocationBeanDao getLocationBeanDao() {
        return locationBeanDao;
    }

}
