package com.itraing.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEVICE_BEAN.
 */
public class DeviceBean {

    /** Not-null value. */
    private String UUIDString;
    /** Not-null value. */
    private String tagName;
    /** Not-null value. */
    private String imageName;
    private int warnVoiceLevel;
    private int findVoiceLevel;
    private boolean warnLight;
    private boolean findLight;
    /** Not-null value. */
    private String warnVoice;
    /** Not-null value. */
    private String findVoice;
    private boolean warnStatus;

    public DeviceBean() {
    }

    public DeviceBean(String UUIDString) {
        this.UUIDString = UUIDString;
    }

    public DeviceBean(String UUIDString, String tagName, String imageName, int warnVoiceLevel, int findVoiceLevel, boolean warnLight, boolean findLight, String warnVoice, String findVoice, boolean warnStatus) {
        this.UUIDString = UUIDString;
        this.tagName = tagName;
        this.imageName = imageName;
        this.warnVoiceLevel = warnVoiceLevel;
        this.findVoiceLevel = findVoiceLevel;
        this.warnLight = warnLight;
        this.findLight = findLight;
        this.warnVoice = warnVoice;
        this.findVoice = findVoice;
        this.warnStatus = warnStatus;
    }

    /** Not-null value. */
    public String getUUIDString() {
        return UUIDString;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUUIDString(String UUIDString) {
        this.UUIDString = UUIDString;
    }

    /** Not-null value. */
    public String getTagName() {
        return tagName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /** Not-null value. */
    public String getImageName() {
        return imageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public int getWarnVoiceLevel() {
        return warnVoiceLevel;
    }

    public void setWarnVoiceLevel(int warnVoiceLevel) {
        this.warnVoiceLevel = warnVoiceLevel;
    }

    public int getFindVoiceLevel() {
        return findVoiceLevel;
    }

    public void setFindVoiceLevel(int findVoiceLevel) {
        this.findVoiceLevel = findVoiceLevel;
    }

    public boolean getWarnLight() {
        return warnLight;
    }

    public void setWarnLight(boolean warnLight) {
        this.warnLight = warnLight;
    }

    public boolean getFindLight() {
        return findLight;
    }

    public void setFindLight(boolean findLight) {
        this.findLight = findLight;
    }

    /** Not-null value. */
    public String getWarnVoice() {
        return warnVoice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWarnVoice(String warnVoice) {
        this.warnVoice = warnVoice;
    }

    /** Not-null value. */
    public String getFindVoice() {
        return findVoice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFindVoice(String findVoice) {
        this.findVoice = findVoice;
    }

    public boolean getWarnStatus() {
        return warnStatus;
    }

    public void setWarnStatus(boolean warnStatus) {
        this.warnStatus = warnStatus;
    }

}
