package com.itraing.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.itraing.greendao.LostBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LOST_BEAN.
*/
public class LostBeanDao extends AbstractDao<LostBean, Long> {

    public static final String TABLENAME = "LOST_BEAN";

    /**
     * Properties of entity LostBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UUIDString = new Property(1, String.class, "UUIDString", false, "UUIDSTRING");
        public final static Property TagName = new Property(2, String.class, "tagName", false, "TAG_NAME");
        public final static Property ImageName = new Property(3, String.class, "imageName", false, "IMAGE_NAME");
        public final static Property LostTime = new Property(4, java.util.Date.class, "lostTime", false, "LOST_TIME");
        public final static Property LostYear = new Property(5, int.class, "lostYear", false, "LOST_YEAR");
        public final static Property LostMonth = new Property(6, int.class, "lostMonth", false, "LOST_MONTH");
        public final static Property LostDay = new Property(7, int.class, "lostDay", false, "LOST_DAY");
        public final static Property LostLot = new Property(8, double.class, "lostLot", false, "LOST_LOT");
        public final static Property LostLat = new Property(9, double.class, "lostLat", false, "LOST_LAT");
        public final static Property LostAddress = new Property(10, String.class, "lostAddress", false, "LOST_ADDRESS");
    };


    public LostBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LostBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LOST_BEAN' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'UUIDSTRING' TEXT NOT NULL ," + // 1: UUIDString
                "'TAG_NAME' TEXT NOT NULL ," + // 2: tagName
                "'IMAGE_NAME' TEXT NOT NULL ," + // 3: imageName
                "'LOST_TIME' INTEGER NOT NULL ," + // 4: lostTime
                "'LOST_YEAR' INTEGER NOT NULL ," + // 5: lostYear
                "'LOST_MONTH' INTEGER NOT NULL ," + // 6: lostMonth
                "'LOST_DAY' INTEGER NOT NULL ," + // 7: lostDay
                "'LOST_LOT' REAL NOT NULL ," + // 8: lostLot
                "'LOST_LAT' REAL NOT NULL ," + // 9: lostLat
                "'LOST_ADDRESS' TEXT NOT NULL );"); // 10: lostAddress
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LOST_BEAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LostBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUUIDString());
        stmt.bindString(3, entity.getTagName());
        stmt.bindString(4, entity.getImageName());
        stmt.bindLong(5, entity.getLostTime().getTime());
        stmt.bindLong(6, entity.getLostYear());
        stmt.bindLong(7, entity.getLostMonth());
        stmt.bindLong(8, entity.getLostDay());
        stmt.bindDouble(9, entity.getLostLot());
        stmt.bindDouble(10, entity.getLostLat());
        stmt.bindString(11, entity.getLostAddress());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LostBean readEntity(Cursor cursor, int offset) {
        LostBean entity = new LostBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // UUIDString
            cursor.getString(offset + 2), // tagName
            cursor.getString(offset + 3), // imageName
            new java.util.Date(cursor.getLong(offset + 4)), // lostTime
            cursor.getInt(offset + 5), // lostYear
            cursor.getInt(offset + 6), // lostMonth
            cursor.getInt(offset + 7), // lostDay
            cursor.getDouble(offset + 8), // lostLot
            cursor.getDouble(offset + 9), // lostLat
            cursor.getString(offset + 10) // lostAddress
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LostBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUUIDString(cursor.getString(offset + 1));
        entity.setTagName(cursor.getString(offset + 2));
        entity.setImageName(cursor.getString(offset + 3));
        entity.setLostTime(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setLostYear(cursor.getInt(offset + 5));
        entity.setLostMonth(cursor.getInt(offset + 6));
        entity.setLostDay(cursor.getInt(offset + 7));
        entity.setLostLot(cursor.getDouble(offset + 8));
        entity.setLostLat(cursor.getDouble(offset + 9));
        entity.setLostAddress(cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LostBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LostBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
